version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  remindme:
    image: "trevorold/mvp-remind-me:latest"   
    working_dir: /usr/src/app
    environment:
      MONGO: mongodb://mongo:27017/remindMe
      PORT: 3000
    ports:
      - 3000:3000
    command: "npm start"